USE [master]
GO

/****** Object:  Database [CM]    Script Date: 27-08-2019 03:15:20 ******/
DROP DATABASE [CM]
GO

/****** Object:  Database [CM]    Script Date: 27-08-2019 03:15:20 ******/
CREATE DATABASE [CM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CM] SET ARITHABORT OFF 
GO

ALTER DATABASE [CM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CM] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CM] SET  MULTI_USER 
GO

ALTER DATABASE [CM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CM] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CM] SET  READ_WRITE 
GO


